CREATE TABLE public.tasks
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title       VARCHAR(255)                            NOT NULL,
    description VARCHAR(1024),
    status      VARCHAR(255)                            NOT NULL,
    priority    VARCHAR(255)                            NOT NULL,
    creator     BIGINT,
    executor    BIGINT,
    created_at  TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    update_at   TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_tasks PRIMARY KEY (id)
);

ALTER TABLE public.tasks
    ADD CONSTRAINT FK_TASKS_ON_CREATOR FOREIGN KEY (creator) REFERENCES public.users (id)
    ON UPDATE NO ACTION ON DELETE CASCADE;

ALTER TABLE public.tasks
    ADD CONSTRAINT FK_TASKS_ON_EXECUTOR FOREIGN KEY (executor) REFERENCES public.users (id)
    ON UPDATE NO ACTION ON DELETE CASCADE;